version: "3.8"
services:
  code_tanks_game_server:
    container_name: code_tanks_game_server
    build:
      context: ../../
      dockerfile: DockerfileGameServer
    ports:
      - 9899:9899
    environment: 
      - AUTHENTICATION_SERVER_URL=ws://192.168.1.98:9897
      - PORT=9899