version: "3.8"
services:
  code_tanks_web_server:
    container_name: code_tanks_web_server
    build:
      context: ../../
      dockerfile: DockerfileWebServer
    ports:
      - 9896:9896
    environment: 
      # - AUTHENTICATION_SERVER_ADDRESS=192.168.1.98
      # - AUTHENTICATION_SERVER_PORT=9897
      - PORT=9896